---

- name: install nginx
  pacman: name=nginx,nginx-mod-brotli,certbot state=present

- name: install nginx.service snippet
  copy: src=nginx.service.d dest=/etc/systemd/system owner=root group=root mode=0644

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: snippets directory
  file: state=directory path=/etc/nginx/snippets owner=root group=root mode=0755

- name: copy snippets
  template: src={{ item }} dest=/etc/nginx/snippets owner=root group=root mode=0644
  with_items:
    - letsencrypt.conf
    - sslsettings.conf
    - headers.conf
  notify:
    - reload nginx

- name: create nginx.d directory
  file: state=directory path=/etc/nginx/nginx.d owner=root group=root mode=0755

- name: create auth directory
  file: state=directory path=/etc/nginx/auth owner=root group=root mode=0755

- name: create default nginx log directory
  file: state=directory path=/var/log/nginx/default owner=root group=root mode=0755

- name: create unique DH group
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048 creates=/etc/ssl/dhparams.pem

- name: create directory to store validation stuff in
  file: owner=root group=http mode=0750 path={{ letsencrypt_validation_dir }} state=directory

- name: install letsencrypt hook
  copy: src=hook.sh dest=/etc/letsencrypt/hook.sh owner=root group=root mode=0755

- name: create letsencrypt hook dir
  file: state=directory path=/etc/letsencrypt/hook.d owner=root group=root mode=0755

- name: install letsencrypt renewal service
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - certbot-renewal.service
    - certbot-renewal.timer
  notify:
    - daemon reload

- name: install logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/nginx-ansible owner=root group=root mode=0644

- name: install inventory_hostname vhost
  template: src=nginx-hostname-vhost.conf.j2 dest=/etc/nginx/nginx.d/nginx-hostname-vhost.conf owner=root group=root mode=0644
  notify:
    - reload nginx
  tags: ['nginx']

- name: activate letsencrypt renewal service
  service: name=certbot-renewal.timer enabled=yes state=started

- name: enable nginx
  service: name=nginx enabled=yes

- name: open firewall holes
  firewalld: service={{item}} permanent=true state=enabled immediate=yes
  with_items:
    - http
    - https
  when: configure_firewall
  tags:
    - firewall
