---

- name: setup dragon
  hosts: dragon.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: archusers }
    - { role: sudo, tags: ['archusers'] }
    - { role: syncrepo }
    - { role: sogrep }
    - { role: archbuild }
    - { role: docker_image }
    - { role: fail2ban }
    - { role: prometheus_exporters }
